CREATE TABLE IF NOT EXISTS "Library" (
	"Id"	        	INTEGER NOT NULL UNIQUE,
	"BookId"			INTEGER NOT NULL UNIQUE,
	PRIMARY KEY("Id" AUTOINCREMENT),
    FOREIGN KEY("BookId") REFERENCES "Books"("Id")
);
